feat: findPackage

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -7,50 +7,57 @@ trigger:
 - master
 
 variables:
-  repodir: repo
-  repobranch: master
+  repoDir: repo
+  repoBranch: master
+  repoUrl: https://github.com/favoyang/unity-package-example-subtree.git
+  packageName: com.namespace.unitypackageexample-subtree
 
 pool:
   vmImage: 'ubuntu-latest'
 
 steps:
 - script: |
-    echo repodir: $REPODIR
-    echo repobranch: $REPOBRANCH
+    echo repoDir: $REPODIR
+    echo repoBranch: $REPOBRANCH
+    echo packageName: $PACKAGENAME
     [[ -z "$REPODIR" ]] && echo '$REPODIR not found' && exit 1
     [[ -z "$REPOBRANCH" ]] && echo '$REPOBRANCH not found' && exit 1
+    [[ -z "$PACKAGENAME" ]] && echo '$PACKAGENAME not found' && exit 1
     exit 0
   displayName: 'Print environment'
 
+- task: NodeTool@0
+  inputs:
+    versionSpec: '10.x'
+  displayName: 'Install Node.js'
+
+- task: Npm@1
+  inputs:
+    command: install
+  displayName: 'Install dependencies'
+
 - script: |
-    echo test
-  displayName: 'next $(repodir)'
+    git clone --depth 1 --branch $(repoBranch) $(repoUrl) $(repoDir)
+    cd $(repoDir)
+  displayName: 'Clone $(repoDir) repository'
 
-# - powershell: |
-#     Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
-#     Write-Host "##vso[task.complete result=Canceled;]DONE"
-#   condition: and(succeeded(), or(eq(variables['repogit'], ''), eq(variables['repobranch'], '')))
-#   displayName: 'Verify environment'
+- script: |
+    PACKAGEFOLDER=`node findPackage.js $(packageName) $(repoDir)`
+    if [[ -z "$PACKAGEFOLDER" ]]; then
+      echo "WARN: no valid package.json found, fallback to $(repoDir)"
+      PACKAGEFOLDER=$(repoDir)
+    fi
+    echo PACKAGEFOLDER: $PACKAGEFOLDER
+    echo "##vso[task.setvariable variable=packageFolder;]$PACKAGEFOLDER"
+  displayName: 'Detect package folder'
 
-# - task: NodeTool@0
-#   inputs:
-#     versionSpec: '10.x'
-#   displayName: 'Install Node.js'
-
-# - task: DeleteFiles@1
-#   inputs:
-#     contents: $(repogit)
-#   displayName: 'Clean target folder'
-
-# - script: |
-#     git clone --depth 1 --branch $(repobranch) $(repogit) $(repodir)
-#     cd $(repodir)
-#   displayName: 'Clone target repository'
+- script: echo $(packageFolder)
+  displayName: 'packageFolder is $(packageFolder)'
 
 # - task: Npm@1
 #   inputs:
 #      command: publish
-#      workingDir: $(repodir)
+#      workingDir: $(repoDir)
 #      publishRegistry: useExternalRegistry
 #      publishEndpoint: openupm
 #   displayName: 'Publish to OpenUPM'
