fix: test pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,7 +9,6 @@ trigger:
 variables:
   repodir: repo
   repobranch: master
-  repourl:
 
 pool:
   vmImage: 'ubuntu-latest'
@@ -17,16 +16,14 @@ pool:
 steps:
 - script: |
     echo repodir: $REPODIR
-    [[ -z "$REPODIR" ]] && echo '$REPODIR not found' && exit 1
-    echo repourl: $REPOURL
-    [[ -z "$REPOURL" ]] && echo '$REPOURL not found' && exit 1
     echo repobranch: $REPOBRANCH
+    [[ -z "$REPODIR" ]] && echo '$REPODIR not found' && exit 1
     [[ -z "$REPOBRANCH" ]] && echo '$REPOBRANCH not found' && exit 1
   displayName: 'Print environment'
 
 - script: |
     echo test
-  displayName: 'next'
+  displayName: 'next $(repodir)'
 
 # - powershell: |
 #     Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
