fix ci

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,9 +19,11 @@ steps:
 - script: |
     echo repoDir: $REPODIR
     echo repoBranch: $REPOBRANCH
+    echo repoUrl: $REPOURL
     echo packageName: $PACKAGENAME
     [[ -z "$REPODIR" ]] && echo '$REPODIR not found' && exit 1
     [[ -z "$REPOBRANCH" ]] && echo '$REPOBRANCH not found' && exit 1
+    [[ -z "$REPOURL" ]] && echo '$REPOURL not found' && exit 1
     [[ -z "$PACKAGENAME" ]] && echo '$PACKAGENAME not found' && exit 1
     exit 0
   displayName: 'Print environment'
@@ -49,10 +51,7 @@ steps:
     fi
     echo PACKAGEFOLDER: $PACKAGEFOLDER
     echo "##vso[task.setvariable variable=packageFolder;]$PACKAGEFOLDER"
-  displayName: 'Detect package folder'
-
-- script: echo $(packageFolder)
-  displayName: 'packageFolder is $(packageFolder)'
+  displayName: 'Detect $(packageFolder)'
 
 # - task: Npm@1
 #   inputs:
